title: qarbyte
# domain: ikarthikmb.github.io
# url: https://ikarthikmb.github.io
# baseurl: /ikarthikmb/
author:
  name: Karthik Mahendra
  email: b.karthikmahendra@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  A system log regarding chip design, reverse engineering, and electronic experiments.

terminal:
  user: "root@qarbyte"
  path: "~$"
  footer_command: "help site"

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  skin: slate

  # generate social links in footer
  social_links:
    twitter_username: qrthik
    github_username:  ikarthikmb
    linkedin_username: 
    hdlbits_username:
    medium_username:
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: karthik-mb
    # pinterest: jekyll
    # youtube: jekyll
    youtube_channel: UCv-uZxa_Zr7OCYs1Wu35RjA
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - silicon.md
 - projects.md
 - logs.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

collections:
  silicon:
    output: true
  projects:
    output: true
  logs:
    output: true

navigation:
    - title: "Index"
      url: "/"
    - title: "Silicon"
      url: "/silicon/"
    - title: "projects"
      url: "/projects/"
    - title: "logs"
      url: "/logs/"

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: post
  - scope:
      path: ""
      type: logs
    values:
      layout: post

layouts_dir: _layouts

comments_repo: ikarthikmb/ikarthikmb.github.io

include:
  - _papers
